EB-0-chore: main branch checks

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -11,8 +11,8 @@ COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
 ALLOWED_TYPES="feat|fix|docs|style|refactor|test|chore"
 
 # Validate the commit message format
-if ! echo "$COMMIT_MSG" | grep -qE "^PC-[0-9]+-($ALLOWED_TYPES): .+"; then
-  echo "ERROR: Commit message must follow the format 'PC-<number>-<type>: <message>'"
+if ! echo "$COMMIT_MSG" | grep -qE "^EB-[0-9]+-($ALLOWED_TYPES): .+"; then
+  echo "ERROR: Commit message must follow the format 'EB-<number>-<type>: <message>'"
   echo "Allowed types are: feat, fix, docs, style, refactor, test, chore"
   exit 1
 fi
